server:
  port: 8090

spring:
  application:
    name: loans
  profiles:
    active: qa
  config:
    import: optional:configserver:http://localhost:8071/
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"