services:
  configserver:
    image: sagarkancharla/configserver:s8
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  eurekaserver:
    image: sagarkancharla/eurekaserver:s8
    container_name: eurekaserver-ms
    ports:
      - 8070:8070
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: eurekaserver

  accounts:
    image: sagarkancharla/accounts:s8
    container_name: accounts-ms
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  cards:
    image: sagarkancharla/cards:s8
    container_name: cards-ms
    ports:
      - 9000:9000
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  loans:
    image: sagarkancharla/loans:s8
    container_name: loans-ms
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: bridge
