server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        git :
          uri: https://github.com/sagarkancharla/eazybytes-config.git
          default-label: main
          time-out: 5
          cloneOnStart: true
          force-pull: true
        #native:
          #search-locations: classpath:/config
          #search-locations: file:/D:/Sagar/docs/config

encrypt:
  key: e9t0y1u4h8f6j7d6x4n1

management:
  endpoints:
    web:
      exposure:
        include: "*"